apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration
          image: jayoh712/monitoring-db-migration
      restartPolicy: OnFailure
