# Service definition for NestJS App
apiVersion: v1
kind: Service
metadata:
  name: nestjs-service
spec:
  selector:
    app: nestjs-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodeport는 나중에 ingress로 바꿔야 함. 일단 이게 중요한 게 아니니까 외부로 노출만이라도 시키자
      nodePort: 30040
   type: NodePort
---
# Deployment for NestJS App
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: nestjs-app
          image: jayoh712/monitoring-app
          ports:
            - containerPort: 3000
