apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
        - name: migration
          image: your-migration-image # 마이그레이션을 실행할 수 있는 이미지를 지정해야 합니다.
          command:
            [
              "npx",
              "ts-node",
              "-r",
              "tsconfig-paths/register",
              "node_modules/.bin/mikro-orm",
              "migration:up",
            ]
      restartPolicy: OnFailure
