FROM node:16-slim

WORKDIR /app

# 빌드된 결과물과 설정 파일들을 복사합니다.
COPY ./dist/*.js ./dist/
COPY ./src/migrations ./src/migrations
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock

# 실행에 필요한 종속성만 설치합니다.
RUN yarn install

# 마이그레이션을 실행하는 명령어를 지정합니다.
CMD ["yarn", "mikro-orm:update"]
